SELECT TOP (1000) [id]
      ,[states]
      ,[gross_income]
      ,[pension_contribution]
      ,[consolidated_relief_allowance]
      ,[taxable_income]
      ,[income_tax]
      ,[total_deductions]
      ,[net_income]
  FROM [Income Tax].[dbo].[tax_calculations]
